-- 고객 테이블
CREATE TABLE CUSTOMER_TB (
    CUS_NO NUMBER PRIMARY KEY,
    CUS_NAME VARCHAR2(20) NOT NULL,
    CUS_GENDER VARCHAR2(1) NOT NULL,
    CUS_AGE NUMBER,
    CUS_RESINUM VARCHAR2(15) NOT NULL,
    CUS_ADDRESS VARCHAR2(80) NOT NULL,
    CUS_PHONE NUMBER,
    CUS_EMAIL VARCHAR2(30),
    CUS_JOB CHAR(1) DEFAULT 'Y' CHECK(CUS_JOB IN ('Y', 'N')),
    LOAN CHAR(1) DEFAULT 'N' CHECK(LOAN IN ('N', 'Y')),
    AMOUNT NUMBER DEFAULT 0.0,
    INTEREST NUMBER,
    RATING NUMBER DEFAULT 6
);

--=================================================
-----------------고객 테이블 코멘트------------------
COMMENT ON COLUMN CUSTOMMER_TB.CUS_NO IS '고객번호';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_NAME IS '고객명';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_GENDER IS '고객성별';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_AGE IS '고객나이';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_RESINUM IS '고객주민번호';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_ADDRESS IS '고객주소';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_PHONE IS '고객연락처';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_EMAIL IS '고객이메일';
COMMENT ON COLUMN CUSTOMMER_TB.CUS_JOB IS '고객직장';
COMMENT ON COLUMN CUSTOMMER_TB.LOAN IS '대출현황';
COMMENT ON COLUMN CUSTOMMER_TB.AMOUNT IS '대출금액';
COMMENT ON COLUMN CUSTOMMER_TB.INTEREST IS '이자율';
COMMENT ON COLUMN CUSTOMMER_TB.RATING IS '신용등급';

--=================================================
------------------ 고객계좌 테이블 ------------------
CREATE TABLE ACCOUNT_TB(
    ACC_NUM CHAR(16) PRIMARY KEY,
    ACC_PWD VARCHAR2(100) NOT NULL,
    CUS_NO NUMBER REFERENCES CUSTOMER_TB(CUS_NO),
    ACC_STATUS CHAR(1) DEFAULT 'Y' CHECK(ACC_STATUS IN ('Y', 'N'))
);

--=================================================
--------------- 고객계좌 테이블 코멘트 ---------------
COMMENT ON COLUMN ACCOUNT_TB.ACC_NUM IS '고객계좌번호';
COMMENT ON COLUMN ACCOUNT_TB.ACC_PWD IS '고객계좌비번';
COMMENT ON COLUMN ACCOUNT_TB.CUS_NO IS '고객번호';
COMMENT ON COLUMN ACCOUNT_TB.ACC_STATUS IS '고객계좌상태';

--=================================================
----------------- 첨부파일 테이블 -------------------
CREATE TABLE ATTACHMENT_TB(
    ATT_NO NUMBER PRIMARY KEY,
    ATT_CHANGENAME VARCHAR2(100),
    ATT_ORIGIN VARCHAR2(100),
    REF_NO NUMBER,
    ATT_CATEGORY NUMBER,
    ATT_FILEPATH VARCHAR2(4000)
);

--=================================================
--------------- 첨부파일 테이블 코멘트 ---------------
COMMENT ON COLUMN ATTACHMENT_TB.ATT_NO IS '첨부파일번호';
COMMENT ON COLUMN ATTACHMENT_TB.ATT_CHANGENAME IS '수정파일명';
COMMENT ON COLUMN ATTACHMENT_TB.ATT_ORIGIN IS '원본파일명';
COMMENT ON COLUMN ATTACHMENT_TB.REF_NO IS '소속글번호';
COMMENT ON COLUMN ATTACHMENT_TB.ATT_CATEGORY IS '참조게시물번호';
COMMENT ON COLUMN ATTACHMENT_TB.ATT_FILEPATH IS '파일경로';


